# Generated by Django 5.1.5 on 2025-02-18 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Listings', '0005_remove_listing_categories_listing_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='categories',
            new_name='category',
        ),
    ]
