# Generated by Django 5.1.5 on 2025-03-03 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Listings', '0006_rename_categories_listing_category'),
        ('Reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='reviews',
            field=models.ManyToManyField(blank=True, related_name='listing_reviews', to='Reviews.review'),
        ),
    ]
